[0m22:34:39.769671 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e537c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b99a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b99ea0>]}


============================== 22:34:39.772025 | 5f95b275-585b-4928-9d7e-3791d42985b5 ==============================
[0m22:34:39.772025 [info ] [MainThread]: Running with dbt=1.6.3
[0m22:34:39.772312 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init duckdbt_setup_emily', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:34:39.772763 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/include/starter_project
[0m22:34:39.776577 [info ] [MainThread]: 
Your new dbt project "duckdbt_setup_emily" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:34:39.776768 [info ] [MainThread]: Setting up your profile.
[0m22:35:16.558658 [error] [MainThread]: Encountered an error:

[0m22:35:16.563480 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 294, in run
    if not self.check_if_can_write_profile(profile_name=profile_name):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 202, in check_if_can_write_profile
    response = click.confirm(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/termui.py", line 237, in confirm
    raise Abort() from None
click.exceptions.Abort

[0m22:35:16.564852 [debug] [MainThread]: Command `dbt init` failed at 22:35:16.564645 after 36.81 seconds
[0m22:35:16.565436 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e537c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b9a140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b9b0a0>]}
[0m22:35:16.566024 [debug] [MainThread]: Flushing usage events
[0m22:38:56.859928 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103937d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10636d9f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10636de70>]}


============================== 22:38:56.862971 | 14d8d6a1-0e30-42f4-885f-db865c3ed835 ==============================
[0m22:38:56.862971 [info ] [MainThread]: Running with dbt=1.6.3
[0m22:38:56.863297 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init duckdbt', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:38:56.863843 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/include/starter_project
[0m22:38:56.866822 [info ] [MainThread]: 
Your new dbt project "duckdbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:38:56.867038 [info ] [MainThread]: Setting up your profile.
[0m22:39:03.006506 [error] [MainThread]: Encountered an error:

[0m22:39:03.010856 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 294, in run
    if not self.check_if_can_write_profile(profile_name=profile_name):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 202, in check_if_can_write_profile
    response = click.confirm(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/termui.py", line 237, in confirm
    raise Abort() from None
click.exceptions.Abort

[0m22:39:03.011784 [debug] [MainThread]: Command `dbt init` failed at 22:39:03.011643 after 6.18 seconds
[0m22:39:03.012200 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103937d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10636f010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10636f040>]}
[0m22:39:03.012703 [debug] [MainThread]: Flushing usage events
[0m16:36:52.236301 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071377c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e69b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e69fc0>]}


============================== 16:36:52.239031 | 3cf062c3-005c-4f37-8198-ea36029d487c ==============================
[0m16:36:52.239031 [info ] [MainThread]: Running with dbt=1.6.3
[0m16:36:52.239334 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:36:52.239627 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/emilyng/Data Engineering/Data Engineering BootCamp/Fish Project/fish_flask_project_ELT_prefect_s3/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:36:52.239930 [debug] [MainThread]: Command `dbt run` failed at 16:36:52.239873 after 0.02 seconds
[0m16:36:52.240089 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071377c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e69ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e6a230>]}
[0m16:36:52.240242 [debug] [MainThread]: Flushing usage events
[0m16:59:07.501074 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e7790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109cdda50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109cdded0>]}


============================== 16:59:07.503970 | 27e3a8a9-7cfc-43ce-b0f0-781e00e1cb7c ==============================
[0m16:59:07.503970 [info ] [MainThread]: Running with dbt=1.6.3
[0m16:59:07.504294 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init duckdbt_fish_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:59:07.504809 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/include/starter_project
[0m16:59:07.508552 [info ] [MainThread]: 
Your new dbt project "duckdbt_fish_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:59:07.508755 [info ] [MainThread]: Setting up your profile.
[0m16:59:32.857982 [error] [MainThread]: Encountered an error:

[0m16:59:32.863118 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 294, in run
    if not self.check_if_can_write_profile(profile_name=profile_name):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 202, in check_if_can_write_profile
    response = click.confirm(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/termui.py", line 237, in confirm
    raise Abort() from None
click.exceptions.Abort

[0m16:59:32.864560 [debug] [MainThread]: Command `dbt init` failed at 16:59:32.864400 after 25.38 seconds
[0m16:59:32.865104 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e7790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109cde1a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109cdf0a0>]}
[0m16:59:32.865627 [debug] [MainThread]: Flushing usage events
[0m17:06:41.036590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1027d7d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1045219c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104521e40>]}


============================== 17:06:41.039434 | 0e76c50d-5b9e-46bd-bf36-1f7670885777 ==============================
[0m17:06:41.039434 [info ] [MainThread]: Running with dbt=1.6.3
[0m17:06:41.039720 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init duckdbt_fish_project_2', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:06:41.040162 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/include/starter_project
[0m17:06:41.044259 [info ] [MainThread]: 
Your new dbt project "duckdbt_fish_project_2" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:06:41.044425 [info ] [MainThread]: Setting up your profile.
[0m17:06:49.614401 [error] [MainThread]: Encountered an error:

[0m17:06:49.621153 [error] [MainThread]: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/cli/main.py", line 469, in init
    results = task.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 307, in run
    adapter = self.ask_for_adapter_choice()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt/task/init.py", line 233, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:06:49.622388 [debug] [MainThread]: Command `dbt init` failed at 17:06:49.622237 after 8.60 seconds
[0m17:06:49.622837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1027d7d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104522fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104522e30>]}
[0m17:06:49.623258 [debug] [MainThread]: Flushing usage events
[0m20:32:18.200720 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104025b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107aa1c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107aa2110>]}


============================== 20:32:18.203792 | d4ff7148-68e1-403d-bf8b-6005ec702b93 ==============================
[0m20:32:18.203792 [info ] [MainThread]: Running with dbt=1.5.8
[0m20:32:18.204132 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m20:32:18.204420 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/emilyng/Data Engineering/Data Engineering BootCamp/Fish Project/fish_flask_project_ELT_prefect_s3/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:32:18.204754 [debug] [MainThread]: Command `dbt run` failed at 20:32:18.204698 after 0.02 seconds
[0m20:32:18.204918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104025b40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107aa2020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107aa21d0>]}
[0m20:32:18.205070 [debug] [MainThread]: Flushing usage events
[0m20:37:22.841481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108025db0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109339f00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10933a380>]}


============================== 20:37:22.844242 | af0f736a-209c-4fd9-8965-68dd71536f26 ==============================
[0m20:37:22.844242 [info ] [MainThread]: Running with dbt=1.5.8
[0m20:37:22.844576 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/emilyng/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m20:37:22.844874 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/emilyng/Data Engineering/Data Engineering BootCamp/Fish Project/fish_flask_project_ELT_prefect_s3/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:37:22.845234 [debug] [MainThread]: Command `dbt run` failed at 20:37:22.845175 after 0.03 seconds
[0m20:37:22.845400 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108025db0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10933a290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10933a440>]}
[0m20:37:22.845547 [debug] [MainThread]: Flushing usage events
[0m16:21:11.611819 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103825d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055a1ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055a2350>]}


============================== 16:21:11.615284 | 2733ac84-8f7d-46bb-8741-765252b0fa4a ==============================
[0m16:21:11.615284 [info ] [MainThread]: Running with dbt=1.5.8
[0m16:21:11.615635 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/emilyng/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m16:21:11.615956 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/emilyng/Data Engineering/Data Engineering BootCamp/Fish Project/fish_tableau_project_ELT_s3_dbt_prefect/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:21:11.616319 [debug] [MainThread]: Command `dbt run` failed at 16:21:11.616258 after 0.03 seconds
[0m16:21:11.616486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103825d80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055a2260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1055a2620>]}
[0m16:21:11.616640 [debug] [MainThread]: Flushing usage events
